spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 8998
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
